# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
     inputs: 
      comment: 
        type: string 
        default: "Nuclei V Scan"

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@v2.0.1
        with:
          target: http://testphp.vulnweb.com/

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: nuclei.log
          path: nuclei.log
